### ISSUE TITLE
Question about batch data 

### ISSUE THREAD

**Issue by LArab401** [sesenosannko/dcnn_textvae#2]
Hi, 
  In your batchloader.py, you use the numpy.random.integers() function to get each batch of data. But I wonder that some batches of data will be uesd many times while some batches of data won't be used at all.  Don't this affect your experimental results? Also repeated data in test dataset is not reasonable. 
  Looking forward to your reply.
  PS：I don't know if I express myself clearly, hope you don't mind.

**Comment by ryokamoi** [comment]
Hi,
Feeding strategy is already fixed in the latest version (of my local directory).
I will push them soon.

As you mentions, it is definitely not a good strategy especially for the test phase. You should modify it if you want to get precise/unchanging evaluation.

However, for training, I do not think it causes serious problems. Feeding data in random order during training is a popular method. Although it may be better to ensure that one training data is used exactly once in one epoch, my simplified implementation may not have a major effect on the result.

Any comments, let me know.
Thanks,

**Comment by LArab401** [comment]
Thank you very much for your reply.
I may have misunderstood your code. In the train_cvae.py,  In the "if batch ==9 or batch %100 ==99" part. the code under comment "sample output" is actually working as  valid process, there is no test part, right? And what's the purpose of the "#debug" part?

**Comment by ryokamoi** [comment]
"sample output" calculates validation score, but each of the scores is inaccurate since it is calculated with one mini-batch. It allows you to see the overview when you see accumulated scores with tensorboard.

The "#debug"part generates text from the same text as a sample of training output. Its purpose is to make sure that the implementation of validation phase is correct (you can ignore it).
